ARG BASE_IMAGE="registry.fedoraproject.org/fedora"
ARG FEDORA_VERSION="${FEDORA_VERSION:-39}"

FROM ${BASE_IMAGE}:${FEDORA_VERSION} as builder

COPY files /tmp/files
COPY container-policy.spec /tmp/specs/container-policy.spec

RUN dnf install \
	--disablerepo='*' \
	--enablerepo='fedora,updates' \
	--setopt install_weak_deps=0 \
	--nodocs \
	--assumeyes \
	rpm-build

RUN mkdir -p /var/cache/rpms/container-policy /tmp/container-policy/rpmbuild/SOURCES
RUN tar -czf /tmp/container-policy/rpmbuild/SOURCES/container-policy.tar.gz -C /tmp files

RUN rpmbuild -ba \
	--define '_topdir /tmp/container-policy/rpmbuild' \
	--define '%_tmppath %{_topdir}/tmp' \
	/tmp/specs/container-policy.spec && \
	cp /tmp/container-policy/rpmbuild/RPMS/noarch/getchoo-container-policy*.rpm /var/cache/rpms/container-policy/

FROM scratch
COPY --from=builder /var/cache/rpms/container-policy /rpms/container-policy
