ARG IMAGE_FLAVOR="${IMAGE_FLAVOR:-getchblue}"
ARG BASE_IMAGE="ghcr.io/getchoo/${IMAGE_FLAVOR}"
ARG FEDORA_VERSION="${FEDORA_VERSION:-39}"
ARG NVIDIA_VERSION="${NVIDIA_VERSION:-535}"

FROM ghcr.io/getchoo/akmods:${FEDORA_VERSION}-${NVIDIA_VERSION} as akmods

FROM ${BASE_IMAGE}:${FEDORA_VERSION} as builder
ARG FEDORA_VERSION
ARG NVIDIA_VERSION

# copy our signed artifacts over
COPY --from=akmods /rpms /tmp/akmods

# install our pub cert to import, along with signed kmods
RUN rpm-ostree install \
	/tmp/akmods/akmods-cert/getchoo-akmods-cert*.rpm \
	xorg-x11-drv-nvidia-{cuda,power}-${NVIDIA_VERSION}* \
	nvidia-vaapi-driver \
	/tmp/akmods/kmods/kmod-nvidia-*.rpm

RUN rpm-ostree cleanup -m && \
	rm -rf /tmp/* /var/* && \
	ostree container commit
