ARG IMAGE_FLAVOR="${IMAGE_FLAVOR:-getchblue}"
ARG BASE_IMAGE="ghcr.io/getchoo/${IMAGE_FLAVOR}"
ARG FEDORA_VERSION="${FEDORA_VERSION:-39}"

FROM ${BASE_IMAGE}:${FEDORA_VERSION} as nvidia
ARG FEDORA_VERSION="${FEDORA_VERSION:-39}"
ARG NVIDIA_VERSION="${NVIDIA_VERSION:-535}"

COPY install.sh /tmp/install.sh
COPY --from ghcr.io/getchoo/akmods:${FEDORA_VERSION}-${NVIDIA_VERSION} /rpms /tmp/akmods

RUN /tmp/install.sh ${NVIDIA_VERSION} && rpm-ostree cleanup -m && \
	rm -rf /tmp/* /var/* && ostree container commit
