name: Build images

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  pull_request:
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  akmods:
    name: Akmods Image

    permissions:
      contents: read
      id-token: write
      packages: write

    uses: ./.github/workflows/build-image.yaml
    with:
      image_name: akmods
      containerfile: ./akmods/Containerfile
      context: ./akmods
      extra_tags: |
        39-535
      build_args: |
        FEDORA_VERSION=39
        NVIDIA_VERSION=535
    secrets:
      akmods_key: ${{ secrets.AKMODS_KEY }}

  base:
    name: Base Images

    permissions:
      contents: read
      id-token: write
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - image_name: getchblue
            fedora_version: 39
            image_flavor: silverblue

    uses: ./.github/workflows/build-image.yaml
    with:
      image_name: ${{ matrix.image_name }}
      containerfile: ./Containerfile
      context: .
      extra_tags: |
        ${{ matrix.fedora_version }}
      build_args: |
        FEDORA_VERSION=${{ matrix.fedora_version }}
        IMAGE_FLAVOR=${{ matrix.image_flavor }}

  nvidia:
    name: NVIDIA Images
    needs: [akmods, base]

    permissions:
      contents: read
      id-token: write
      packages: write

    strategy:
      fail-fast: false
      matrix:
        include:
          - image_flavor: getchblue 
            fedora_version: 39
            nvidia_version: 535

    uses: ./.github/workflows/build-image.yaml
    with:
      image_name: ${{ matrix.image_flavor }}-nvidia
      containerfile: ./nvidia/Containerfile
      context: ./nvidia
      extra_tags: |
        ${{ matrix.fedora_version }}-${{ matrix.nvidia_version }}
      build_args: |
        FEDORA_VERSION=${{ matrix.fedora_version }}
        IMAGE_FLAVOR=${{ matrix.image_flavor }}
        NVIDIA_VERSION=${{ matrix.nvidia_version }}
