ARG BASE_IMAGE="quay.io/fedora-ostree-desktops/base"
ARG FEDORA_VERSION="${FEDORA_VERSION:-39}"

FROM ${BASE_IMAGE}:${FEDORA_VERSION} as builder
ARG NVIDIA_VERSION="${NVIDIA_VERSION:-535}"

COPY prep.sh /tmp/prep.sh
COPY build_*.sh /tmp
COPY install.sh /tmp/install.sh
COPY certs /tmp/certs
COPY akmods-cert.spec /tmp/akmods-cert/akmods-cert.spec

RUN /tmp/prep.sh

RUN /tmp/build_nvidia.sh ${NVIDIA_VERSION}
RUN /tmp/build_cert.sh

RUN /tmp/install.sh

FROM scratch
COPY --from=builder /var/cache/rpms /rpms
